FROM ubuntu:latest

RUN apt update
RUN apt install python3-pip -y
RUN pip3 install numpy
RUN pip3 install flask
RUN pip3 install tensorflow
RUN pip3 install pillow
RUN pip3 install yfinance
RUN pip3 install pandas
RUN pip3 install scikit-learn

WORKDIR /app

COPY . .

CMD ["python3", "-m" , "flask", "run", "--host=0.0.0.0"]